- type: gameMap
  id: Train
  mapName: 'Train'
  mapPath: /Maps/train.yml
  minPlayers: 10
  maxPlayers: 50
  stations:
    Train:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: 'Train "Sentipode" {0}-{1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'ED'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/Shuttles/emergency_omega.yml # To do - add railway station
<<<<<<< HEAD
========
  id: BoxGanimed
  mapName: 'Box Station'
  mapPath: /Maps/Ganimed/box.yml
  minPlayers: 30
  maxPlayers: 65
  stations:
    BoxGanimed:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: '{0} Бокс {1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'ИСН'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/Shuttles/emergency_box.yml
>>>>>>>> upstreams:Resources/Prototypes/Maps/Ganimed/box.yml
=======
>>>>>>> upstreams
        - type: StationJobs
          overflowJobs:
            - Passenger
          availableJobs:
            #service
            Captain: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
<<<<<<< HEAD
<<<<<<<< HEAD:Resources/Prototypes/Maps/train.yml
=======
>>>>>>> upstreams
            Bartender: [ 1, 1 ]
            Botanist: [ 2, 2 ]
            Chef: [ 1, 1 ]
            Janitor: [ 1, 2 ]
            Chaplain: [ 1, 1 ]
            Librarian: [ 1, 1 ]
            ServiceWorker: [ 2, 3 ]
            Detective: [ 1, 1 ]
<<<<<<< HEAD
========
            Bartender: [ 2, 2 ]
            Botanist: [ 3, 3 ]
            Chef: [ 2, 2 ]
            Janitor: [ 2, 2 ]
            Chaplain: [ 1, 1 ]
            Librarian: [ 1, 1 ]
            ServiceWorker: [ 2, 2 ]
>>>>>>>> upstreams:Resources/Prototypes/Maps/Ganimed/box.yml
=======
>>>>>>> upstreams
            #engineering
            ChiefEngineer: [ 1, 1 ]
            AtmosphericTechnician: [ 3, 3 ]
            StationEngineer: [ 5, 5 ]
<<<<<<< HEAD
<<<<<<<< HEAD:Resources/Prototypes/Maps/train.yml
=======
>>>>>>> upstreams
            TechnicalAssistant: [ 3, 3 ]
            #medical
            ChiefMedicalOfficer: [ 1, 1 ]
            Chemist: [ 2, 2 ]
            MedicalDoctor: [ 3, 3 ]
            MedicalIntern: [ 2, 2 ]
            #science
            ResearchDirector: [ 1, 1 ]
            Scientist: [ 4, 4 ]
            ResearchAssistant: [ 2, 2 ]
            #security
            HeadOfSecurity: [ 1, 1 ]
            Warden: [ 1, 1 ]
            SecurityOfficer: [ 4, 4 ]
            SecurityCadet: [ 2, 3 ]
            Lawyer: [ 1, 2 ]
            #supply
            Quartermaster: [ 1, 1 ]
            SalvageSpecialist: [ 2, 2 ]
            CargoTechnician: [ 2, 2 ]
<<<<<<< HEAD
========
            TechnicalAssistant: [ 4, 4 ]
            #medical
            ChiefMedicalOfficer: [ 1, 1 ]
            Chemist: [ 2, 3 ]
            MedicalDoctor: [ 4, 4 ]
            Paramedic: [ 1, 1 ]
            MedicalIntern: [ 4, 4 ]
            Psychologist: [ 1, 1 ]
            #science
            ResearchDirector: [ 1, 1 ]
            Scientist: [ 5, 5 ]
            ResearchAssistant: [ 4, 4 ]
            Borg: [ 2, 2 ]
            #security
            HeadOfSecurity: [ 1, 1 ]
            Warden: [ 1, 1 ]
            SecurityOfficer: [ 5, 5 ]
            Detective: [ 1, 1 ]
            SecurityCadet: [ 4, 4 ]
            Lawyer: [ 2, 2 ]
            #supply
            Quartermaster: [ 1, 1 ]
            SalvageSpecialist: [ 3, 3 ]
            CargoTechnician: [ 3, 3 ]
>>>>>>>> upstreams:Resources/Prototypes/Maps/Ganimed/box.yml
=======
>>>>>>> upstreams
            #civilian
            Passenger: [ -1, -1 ]
            Clown: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 1 ]
<<<<<<< HEAD
<<<<<<<< HEAD:Resources/Prototypes/Maps/train.yml
            Borg: [ 2, 2 ]
========
            #enterprise-rework
            SeniorPhysician: [ 1, 1 ]
            SeniorEngineer: [ 1, 1 ]
            SeniorResearcher: [ 1, 1 ]
            SeniorOfficer: [ 1, 1 ]
            BlueShield: [ 1, 1 ]
            Roboticist: [ 1, 1 ]
            Brigmedic: [ 1, 1 ]
            Prisoner: [ 3, 0 ]
            IAA: [ 1, 1 ]
            Coroner: [ 1, 1 ]
            Boxer: [ 1, 1 ]
            BridgeOfficer: [ 0, 1 ]
>>>>>>>> upstreams:Resources/Prototypes/Maps/Ganimed/box.yml
=======
            Borg: [ 2, 2 ]
            #ent
            SeniorPhysician: [ 0, 1 ]
            SeniorEngineer: [ 0, 1 ]
            SeniorResearcher: [ 0, 1 ]
            SeniorOfficer: [ 0, 1 ]
            BlueShield: [ 0, 1 ]
            Roboticist: [ 0, 1 ]
            Brigmedic: [ 0, 1 ]
            IAA: [ 0, 1 ]
            Coroner: [ 0, 1 ]
            BridgeOfficer: [ 0, 1 ]

>>>>>>> upstreams
