- type: gameMapPool
  id: DefaultMapPool
  maps:
  - CorvaxAvrite
  - CorvaxDelta
  - CorvaxGate
  - CorvaxIshimura
  - CorvaxSilly
  - Europa
  - Fland
  - Gemini
  - Atlas
  - Cluster
  - Bagel
  - Aspid
  - Barratry
  - Box
  - Core
  - Marathon
  - Meta
  - Omega
  - Origin
  - Saltern
  - Packed
  - Spectrum
