#Cult outfit startingGear definitions.
- type: startingGear
  id: CultLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpack
    head: ClothingHeadHelmetCult
    neck: BedsheetCult
    outerClothing: ClothingOuterArmorCult
    shoes: ClothingShoesCult
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: CultistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpack
    head: ClothingHeadHatHoodCulthood
    outerClothing: ClothingOuterRobesCult
    shoes: ClothingShoesColorRed
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
